#!/bin/sh
/etc/init.d/relayd enabled && /etc/init.d/relayd start

# enable access from client network
[ "$INTERFACE" = wwan ] || exit 0
[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0

. /lib/functions/network.sh; network_get_ipaddr ip wwan;

uci set network.stabridge.ipaddr=$ip
uci commit network
